helpdesk/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('login', views.login_page, name='login_page'),
    path('logout', views.logout_page, name='logout_page'),
    path('addtask', views.addtask_page, name='addtask_page'),
    path('posttask', views.posttask_page, name='posttask_page'),
    path('taskdetails/<int:pk>/', views.taskdetails_page, name='taskdetails_page'),
    path('taskdetails/<int:pk>/commentdelete/<int:comm_pk>', views.deletecomment_page, name='deletecomment_page'),
    path('deletetask/<int:pk>/', views.deletetask_page, name='deletetask_page'),
    path('closetask/<int:pk>/', views.closetask_page, name='closetask_page'),
]

tickets/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdesk.urls')),
]

helpdesk/models.py
from django.db import models
from datetime import datetime
import boto3
from django.conf import settings
from django.contrib.auth.models import User
from dotenv import load_dotenv

load_dotenv()

PRIORITY_CHOICES = (
    ('Niski','Niski'),
    ('Normalny', 'Normalny'),
    ('Wysoki','Wysoki'),
)

STATUS_CHOICES = (
    ('Stworzono','Stworzono'),
    ('W trakcie','W trakcie'),
    ('Częściowo rozwiązany', 'Częściowo rozwiązany'),
    ('Rozwiązany','Rozwiązany'),
    ('Zamknięty','Zamknięty'),
)

class Task(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False)
    desc = models.TextField(max_length=1000, null=False)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='Niski', null=False)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='Stworzono', null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def publish(self):
        self.save()

    def task_started(self):
        self.status = 'W trakcie'
        return self.save()

    def task_delete(self):
        return self.delete()

    def status_closed(self):
        self.status = 'Zamknięty'
        return

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    text = models.TextField(max_length=2000, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


    def publish(self):
        self.save()

    def comment_delete(self):
        return self.delete()


class Picture(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    file = models.FileField(upload_to='media/', null=False)

    def convert_file_to_path(self, fileObj):
        media_root = 'https://helpdeskpvpl.s3.eu-central-1.amazonaws.com/media/'
        try:
            file_path = fileObj.url
            file_path = file_path.split('/')
            self.file = media_root + file_path[-1]
        except ValueError:
            print('Błąd')



    def picture_delete(self):
        client = boto3.client('s3')
        bucket = os.getenv("DB_NAME")
        path = self.file.url.split('/')[-2:]
        path = '/'.join(path)
        print(path)
        client.delete_object(Bucket=bucket, Key=path)


    def publish(self):
        self.save()

helpdesk/forms.py
from django import forms
from .models import Task, Comment, Picture

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        widgets = {
            'desc': forms.Textarea(attrs={'class': 'desc_area'}),
            'title': forms.TextInput(attrs={'style': 'width: 33%'}),
            'priority': forms.Select(attrs={'class': 'btn btn-secondary dropdown-toggle'}),
        }
        field = ('title', 'desc', 'priority', 'status')
        exclude = ['author', 'status', 'created_at', 'updated_at']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        widgets = {
            'text': forms.Textarea(attrs={'rows': 5, 'cols': 100, 'class': 'form-control ml-1 shadow-none textarea'}),
        }
        labels = {
            "text": "",
        }
        field = ('text')
        exclude = ['author', 'created_at', 'task']


class PictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        labels = {
            "file": "",
        }
        field = ('file')
        exclude = ['comment']

    def __init__(self, *args, **kwargs):
        super(PictureForm, self).__init__(*args, **kwargs)
        self.fields['file'].required = False

helpdesk/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from helpdesk.models import Task, Comment, Picture
from .forms import TaskForm, CommentForm, PictureForm
from datetime import datetime, timezone
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.forms.models import model_to_dict
from django.template import RequestContext
import boto3
import os
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings

STATUSES_DICT = {'Stworzono': 'primary',
                    'W trakcie': 'secondary',
                    'Częściowo rozwiązany': 'warning',
                    'Rozwiązany': 'success',
                    'Zamknięty': 'danger', }

PRIORITY_DICT = {'Niski': 'success',
                 'Normalny': 'warning',
                 'Wysoki': 'danger'}

def login_page(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        userAuth = authenticate(username=username, password=password)
        task_list = Task.objects.all()
        a_time = datetime.now()
        if userAuth is not None:
            login(request, userAuth)
            return redirect('/', {'task_list': task_list,
                                  'a_time': a_time})
        else:
            messages.warning(request, 'Logowanie nie powiodło się.')
            return redirect("login_page")
    return render(request, 'login_page.html')


def home_page(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            task_list = Task.objects.all().order_by('created_at')
        else:
            task_list = Task.objects.filter(author=request.user)
        a_time = datetime.now(timezone.utc)
        return render(request, 'home_page.html', {'task_list': task_list,
                                                  'a_time': a_time,
                                                  'statuses': STATUSES_DICT,
                                                  'priorities': PRIORITY_DICT})
    else:
        return redirect('login_page')


def logout_page(request):
    logout(request)
    messages.success(request, "Zostałeś wylogowany")
    return redirect('home_page')


def addtask_page(request):
    task_form = TaskForm()
    picture_form = PictureForm()
    return render(request, 'addtask_page.html', {'task_form': task_form,
                                                 'picture_form': picture_form})

def deletetask_page(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.task_delete()
    return redirect(request.META['HTTP_REFERER'])

def deletecomment_page(request, comm_pk, pk):
    comment = get_object_or_404(Comment, pk=comm_pk)
    task = get_object_or_404(Task, pk=pk)
    try:
        picture = Picture.objects.get(comment_id=comment.id)
        picture.picture_delete()
    except:
        pass
    comment.comment_delete()
    return redirect(request.META['HTTP_REFERER'])

def closetask_page(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.status_closed()
    task.save()
    return redirect(request.META['HTTP_REFERER'])

def posttask_page(request):
    task_form = TaskForm()
    if request.method == "POST":
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            task.author = request.user
            task.save()
        status = 'Created'
        return redirect('home_page')
    else:
        message = "Nie udało się dodać pliku"
        return render(request, "login_page.html", {'message': message})


def taskdetails_page(request, pk):
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        picture_form = PictureForm(request.POST, request.FILES)
        task = Task.objects.get(pk=pk)
        if comment_form.is_valid():
            print('prawidłowe formy')
            comment = comment_form.save(commit=False)
            picture = picture_form.save(commit=False)
            comment.author = request.user
            comment.task = task
            comment.save()
            task.task_started()
            if picture_form['file'].value() is not None:
                picture.comment = comment
                picture_form.save()
                picture.convert_file_to_path(picture.file)
                picture.save()
            return redirect(request.META['HTTP_REFERER'])
        else:
            messages.success(request, ("Wystąpił błąd podczas logowania, spróbuj ponownie."))
    else:
        task = get_object_or_404(Task, pk=pk)
        a_time = datetime.now(timezone.utc)
        comment_form = CommentForm()
        picture_form = PictureForm()
        comments_list = Comment.objects.filter(task_id=pk).order_by('created_at')
        return render(request, 'helpdesk/taskdetails_page.html', {'task': task,
                                                                  'a_time': a_time,
                                                                  'comment_form': comment_form,
                                                                  'picture_form': picture_form,
                                                                  'statuses': STATUSES_DICT,
                                                                  'comments_list': comments_list,})


# # QUERYSETS
#
# def get_tasks_queryset(query=None):
#     queryset = []
#     queries = query.split(" ")
#     for q in queries:
#         tasks = Task.objects.filter(
#             Q(title_icontrains=q) |
#             Q(created_at_icontrains=q)
#         )
#
#         for task in tasks:
#             queryset.append(post)
#
#         return queryset

helpdesk/templates/helpdesk/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PV Poland Task Manager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/helpdesk.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">

</head>
<body>
<div class="site-title">PV Poland Task Manager</div>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#000;">
        <a class="navbar-brand" href="/homepage" style="margin-bottom: 0.25rem;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href='/'>Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <button type="button" class="btn btn-success mr-2" style="background-color:#0DBF9F;" value="Add file" onclick="location.href='{% url 'addtask_page' %}'">Dodaj zgłoszenie</button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn btn-secondary" onclick="location.href='{% url 'logout_page' %}'">Logout</button>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
</body>

</html>

helpdesk/templates/helpdesk/taskdetails_page.html
{% extends 'helpdesk/base.html' %}
{% block content %}
{% load task_tags %}
{% load text_to_hexcolor from task_tags %}

<div class="container mt-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8" style="text-align: center;">
                <h1>{{ task.title }} <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='{% url 'home_page' %}'">Powrót</button></h1>
                <b>Minęło: {{ task.created_at|timesince:a_time }}</b><br>
                <span class="badge bg-{{statuses|get_item:task.status}}">{{ task.status }}</span>
                <p style="text-align:left;">{{ task.desc }}</p>
        </div>
    </div>
</div>


<div class="container mt-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="d-flex flex-column comment-section">
                {% for comment in comments_list %}
                    <div class="bg-white p-2" style="border-bottom: 2px dotted #c2c2c2;">
                        <div class="d-flex flex-row user-info"><img class="rounded-circle" src="https://ui-avatars.com/api/?name={{ comment.author.username|get_fullname|join:"+" }}&background={{ comment.author.username|get_fullname|text_to_hexcolor }}&color=fff" width="40">
                            <div class="d-flex flex-column justify-content-start ml-2">
                                <span class="d-block font-weight-bold name">{{ comment.author.username|get_fullname|join:" " }}
                                    {% if user == comment.author %}
                                        <a class="fa fa-trash fa-sm" href="{% url 'deletecomment_page' pk=task.id comm_pk=comment.id %}"></a>
                                    {% endif %}
                                </span>
                                <span class="date text-black-50">{{ comment.created_at|date:"d-m-Y H:i" }}</span>
                            </div>
                        </div>
                        <div class="mt-2">
                            <p class="comment-text" style="overflow-wrap: break-word">{{ comment.text }}</p>
                        </div>
                        <div>
                            {% if comment.picture_set.get.file.url %}

                                    <link href="{{ comment.picture_set.get.file }}" rel="stylesheet" type="text/css" />
                                    <a href="#img{{ forloop.counter }}">
                                        <img class="comment-image" src="{{ comment.picture_set.get.file }}">
                                    </a>
                                    <a href="#" class="lightbox" id="img{{ forloop.counter }}">
                                        <span style="background-image: url('{{ comment.picture_set.get.file }}')"></span>
                                    </a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            <form action='' method="POST" style="text-align:center; margin-top:10px;" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="bg-light p-2">
                    <div class="d-flex flex-row align-items-start"><img class="rounded-circle" src="https://ui-avatars.com/api/?name={{ user.username|get_fullname|join:"+" }}&background={{ user.username|get_fullname|text_to_hexcolor }}&color=fff" width="40">{{ comment_form }}</div>
                    <div class="mt-2 text-left">{{ picture_form }}</div>
                    <div class="mt-2 text-right"><button class="btn btn-primary btn-sm shadow-none" type="submit">Dodaj komentarz</button><button class="btn btn-outline-primary btn-sm ml-1 shadow-none" type="button" onclick="location.href='{% url 'home_page' %}'">Powrót</button></div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}